apps:
  - name: akatsuki-twitch-bot
    environment: production
    codebase: akatsuki-twitch-bot
    replicaCount: 1
    container:
      image:
        repository: ghcr.io/osuakatsuki/akatsuki-twitch-bot
        tag: latest
      port: 80
      resources:
        limits:
          cpu: 150m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
      env:
        - name: APP_COMPONENT
          value: bot
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
