import os

TWITCH_ACCESS_TOKEN=os.environ['TWITCH_ACCESS_TOKEN']
TWITCH_COMMAND_PREFIX=os.environ['TWITCH_COMMAND_PREFIX']
BANCHO_SERVICE_CI_KEY=os.environ['BANCHO_SERVICE_CI_KEY']
BANCHO_SERVICE_HOST=os.environ['BANCHO_SERVICE_HOST']
